// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3IIjhkQrDJlRLMs5F9EYsk7z22NlczWk',
    appId: '1:334774364571:web:af0c1e9dc6f52f911f993e',
    messagingSenderId: '334774364571',
    projectId: 'domain-firebase',
    authDomain: 'domain-firebase.firebaseapp.com',
    storageBucket: 'domain-firebase.appspot.com',
    measurementId: 'G-ZFC6CW0HZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjCM5017-AKw7THQB-6Y3fT9JJa_JhOjU',
    appId: '1:334774364571:android:1bc63a6530f697571f993e',
    messagingSenderId: '334774364571',
    projectId: 'domain-firebase',
    storageBucket: 'domain-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJgMCeFTc25Hg5ApqBt7lsYlnJAmdyVTY',
    appId: '1:334774364571:ios:4d2067e9e72f7f9c1f993e',
    messagingSenderId: '334774364571',
    projectId: 'domain-firebase',
    storageBucket: 'domain-firebase.appspot.com',
    iosClientId: '334774364571-k8pl40hns9c4ottjqujt05ovd56jnnkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.domainFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJgMCeFTc25Hg5ApqBt7lsYlnJAmdyVTY',
    appId: '1:334774364571:ios:4d2067e9e72f7f9c1f993e',
    messagingSenderId: '334774364571',
    projectId: 'domain-firebase',
    storageBucket: 'domain-firebase.appspot.com',
    iosClientId: '334774364571-k8pl40hns9c4ottjqujt05ovd56jnnkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.domainFirebase',
  );
}
